name: PR Test on Comment

on:
  issue_comment:
    types: [created]

jobs:
  test:
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, 'test again')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: pnpm install
      - run: pnpm test
